### ISSUE TITLE
项目报错，百度地图 SDK 不完整

### ISSUE THREAD

**Issue by ouyang-yuxuan** [bitkylin/MapForTour#3]

**Comment by bitkylin** [comment]
此项目暂时停更，百度地图SDK在此期间进行了大规模升级，最新的百度地图SDK功能和API均有所改变，并且旧版本的SDK已经被废弃。建议克隆该项目并适配最新的百度地图SDK，或者等待我的进一步更新，谢谢。

**Comment by LCYang163** [comment]
感谢分享！最近正在做一个类似的app，这是个很好的学校资料
